package api

const workspaceHTML = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Mica · Incident workspace</title>
<style>
:root{--ink:#dce7e0;--muted:#9aad9f;--canvas:#101713;--panel:#17221b;--line:#385242;--lime:#a7ec8b;--alert:#ff9c8d;--amber:#f2c46d;font:15px Georgia,serif}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 84% 0,#1e3728 0,transparent 34%),var(--canvas);color:var(--ink)}body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.16;background-image:linear-gradient(#fff1 1px,transparent 1px),linear-gradient(90deg,#fff1 1px,transparent 1px);background-size:28px 28px}.wrap{max-width:1120px;margin:auto;padding:38px 24px 72px;position:relative}header{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:1px solid var(--line);padding-bottom:24px}.kicker{text-transform:uppercase;letter-spacing:.18em;font:11px ui-monospace,monospace;color:var(--lime)}h1,h2{font-weight:400;margin:.25rem 0}h1{font-size:42px;letter-spacing:-.04em}h2{font-size:24px;margin-top:34px}button{appearance:none;background:var(--lime);color:#102113;border:0;border-radius:5px;padding:9px 12px;font:700 12px ui-monospace,monospace;letter-spacing:.03em;cursor:pointer}button:hover{filter:brightness(1.1)}button.secondary{background:transparent;color:var(--ink);border:1px solid var(--line)}button.danger{color:#32100b;background:var(--alert)}.service{color:var(--muted);font:13px ui-monospace,monospace}.empty{margin:70px 0;color:var(--muted);font-size:20px}.grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:24px 0}.card,.panel{background:linear-gradient(135deg,#1b2920,#152019);border:1px solid var(--line);border-radius:7px;padding:15px;box-shadow:0 14px 40px #0003}.signal-value{font:700 28px ui-monospace,monospace;margin:7px 0}.bad{color:var(--alert)}.stable{color:var(--lime)}small,.muted{color:var(--muted);font:12px ui-monospace,monospace}.timeline{border-left:1px solid var(--line);padding-left:21px}.event{position:relative;margin:0 0 19px}.event:before{content:"";position:absolute;left:-26px;top:4px;width:9px;height:9px;border-radius:50%;background:var(--lime);box-shadow:0 0 0 4px var(--canvas)}textarea,input,select{width:100%;background:#101914;border:1px solid var(--line);border-radius:4px;padding:9px;color:var(--ink);font:13px ui-monospace,monospace}.row{display:flex;gap:8px;align-items:end}.row>*{flex:1}.action{display:flex;gap:7px;margin-top:10px}.action button{padding:6px 8px;font-size:10px}.proposal,.update{border-top:1px solid var(--line);padding:14px 0}.proposal:first-child,.update:first-child{border-top:0}.pill{font:10px ui-monospace,monospace;color:var(--amber);border:1px solid #7d6841;border-radius:99px;padding:3px 6px;margin-left:7px}.checks{display:flex;gap:13px;flex-wrap:wrap;padding:7px 0}.checks label{font:12px ui-monospace,monospace;color:var(--muted)}.checks input{width:auto}.hidden{display:none!important}@media(max-width:700px){header{gap:18px;flex-direction:column}.grid{grid-template-columns:1fr}.row{display:block}.row>*{margin:5px 0}}
</style></head><body><div class="wrap"><header><div><div class="kicker">Local production engineering</div><h1>Mica workspace</h1><div class="service" id="service">Loading service context…</div></div><div class="action"><button class="secondary" id="report" disabled>Export report</button><button id="detect">Detect regression</button></div></header>
<main id="empty" class="empty">Run a comparison to open an evidence-backed incident.</main><section id="incident" class="hidden"><div class="grid" id="signals"></div><h2>Shared timeline</h2><div class="timeline" id="timeline"></div><div class="panel"><form id="note"><textarea name="note" placeholder="Add operational context for the investigation"></textarea><div class="action"><button>Add note</button></div></form></div>
<h2>Action proposals</h2><div class="panel" id="proposals"><span class="muted">No proposals recorded.</span></div>
<h2>Audit findings</h2><div class="panel" id="findings"><span class="muted">No audit findings recorded.</span></div>
<h2>Incident communications</h2><div class="panel"><form id="prepare"><div class="row"><label>Update type<select name="updateType"><option value="investigation_update">Investigation update</option><option value="approval_needed">Approval needed</option><option value="mitigation_applied">Mitigation applied</option><option value="recovery_verified">Recovery verified</option><option value="handoff">Handoff</option></select></label><label>Audience<input name="audience" value="engineering"></label></div><div class="checks" id="destinations"></div><div class="action"><button>Prepare redacted preview</button></div></form><div id="updates"></div></div></section></div>
<script>
let current,stream;const q=s=>document.querySelector(s),service=q('#service'),empty=q('#empty'),incident=q('#incident'),signals=q('#signals'),timeline=q('#timeline'),proposals=q('#proposals'),findings=q('#findings'),updates=q('#updates'),report=q('#report');
fetch('/api/services').then(r=>r.json()).then(s=>service.textContent=s[0].name+' · '+s[0].environment+' · '+s[0].dependencies.join(', '));fetch('/api/communications/destinations').then(r=>r.json()).then(d=>q('#destinations').innerHTML=d.map(x=>'<label><input type="checkbox" name="destination" value="'+x.id+'" checked>'+x.provider+'</label>').join(''));
function esc(s){return String(s||'').replace(/[&<>]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]))}function render(data){current=data;empty.classList.add('hidden');incident.classList.remove('hidden');report.disabled=false;signals.innerHTML=data.evidence.map(e=>'<article class="card"><div>'+esc(e.signal)+'</div><div class="signal-value '+(e.classification==='degraded'?'bad':'stable')+'">'+e.incidentValue.toFixed(2)+' '+esc(e.unit)+'</div><small>baseline '+e.baselineValue.toFixed(2)+' · '+e.percentDelta.toFixed(0)+'% · '+esc(e.classification)+'</small><details><summary class="muted">Evidence provenance</summary><small>Query: '+esc(e.query)+'<br>Baseline: '+esc(data.baselineStart)+' → '+esc(data.baselineEnd)+'<br>Incident: '+esc(data.incidentStart)+' → '+esc(data.incidentEnd)+'</small></details></article>').join('');timeline.innerHTML=data.timeline.map(e=>'<div class="event"><strong>'+esc(e.summary)+'</strong><br><small>'+esc(e.actorName)+' · '+new Date(e.occurredAt).toLocaleTimeString()+'</small></div>').join('');proposals.innerHTML=data.proposals.length?data.proposals.map(p=>'<div class="proposal"><strong>'+esc(p.summary)+'</strong><span class="pill">'+esc(p.status)+'</span><p class="muted">Expected: '+esc(p.expectedEffect)+'<br>Risk: '+esc(p.riskStatement)+'<br>Verify: '+esc(p.verificationPlan)+'</p>'+((p.status==='pending_review')?'<div class="action"><button class="secondary" onclick="reviewProposal(\''+p.id+'\',\'reviewed\')">Review</button><button class="secondary" onclick="reviewProposal(\''+p.id+'\',\'deferred\')">Defer</button><button class="danger" onclick="reviewProposal(\''+p.id+'\',\'rejected\')">Reject</button></div>':'')+'</div>').join(''):'<span class="muted">No proposals recorded.</span>';findings.innerHTML=data.auditFindings.length?data.auditFindings.map(f=>'<div class="proposal"><strong>'+esc(f.category)+' · '+esc(f.affectedAsset)+'</strong><span class="pill">'+esc(f.severity)+' / '+esc(f.status)+'</span><p>'+esc(f.assessment)+'</p><p class="muted">Risk: '+esc(f.risk)+'<br>Recommendation: '+esc(f.recommendation)+'<br>Verify: '+esc(f.verificationMethod)+'</p></div>').join(''):'<span class="muted">No audit findings recorded.</span>';updates.innerHTML=data.updates.map(u=>'<div class="update"><strong>'+esc(u.updateType.replaceAll('_',' '))+'</strong><span class="pill">'+esc(u.status)+'</span><pre class="muted">'+esc(u.body)+'</pre><small>Redactions: '+u.redactions.map(esc).join(', ')+'</small><div class="action">'+((u.status==='pending_approval'||u.status==='partially_delivered')?'<button onclick="publishUpdate(\''+u.id+'\')">Approve & publish</button>':'')+'</div></div>').join('')}
function load(){if(current)fetch('/api/incidents/'+current.id).then(r=>r.json()).then(render)}window.reviewProposal=(id,status)=>{const reviewer=prompt('Your name for this review:');if(!reviewer)return;fetch('/api/incidents/'+current.id+'/proposals/'+id+'/review',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({status,reviewer})}).then(r=>r.json()).then(render)};window.publishUpdate=id=>{const approvedBy=prompt('Type your name to explicitly approve this external send:');if(!approvedBy)return;fetch('/api/incidents/'+current.id+'/updates/'+id+'/publish',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({approvedBy})}).then(r=>r.json()).then(render)};
q('#detect').onclick=()=>fetch('/api/incidents/detect',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({serviceId:'checkout'})}).then(r=>r.json()).then(data=>{render(data);if(stream)stream.close();stream=new EventSource('/api/events?incidentId='+data.id);stream.addEventListener('incident-update',load)});q('#note').onsubmit=e=>{e.preventDefault();if(!current)return;const note=e.target.note.value.trim();if(!note)return;fetch('/api/incidents/'+current.id+'/notes',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({note})}).then(r=>r.json()).then(data=>{render(data);e.target.reset()})};q('#prepare').onsubmit=e=>{e.preventDefault();if(!current)return;const form=new FormData(e.target),destinationIds=form.getAll('destination');fetch('/api/incidents/'+current.id+'/updates',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({updateType:form.get('updateType'),audience:form.get('audience'),destinationIds})}).then(r=>r.json()).then(render)};report.onclick=()=>window.open('/api/incidents/'+current.id+'/report','_blank');
setInterval(load,2500);
</script></body></html>`
