import { useEffect, useMemo, useState } from "react"
import type { FormEvent, ReactNode } from "react"
import { AreaChart } from "@/components/dither-kit/area-chart"
import { Area } from "@/components/dither-kit/area"
import { Tooltip } from "@/components/dither-kit/tooltip"
import { XAxis } from "@/components/dither-kit/x-axis"
import "./App.css"
import "./AppV2.css"

type Service={id:string;name:string;environment:string;repository:string;owners:string[];dependencies:string[];runtime?:string;framework?:string;runbooks?:string[];sloRefs?:string[];source?:{kind:string;refreshedAt:string}}
type Evidence={id:string;signal:string;unit:string;query:string;baselineValue:number;incidentValue:number;currentValue?:number;percentDelta:number;classification:string}
type Event={id:string;summary:string;occurredAt:string;actorName?:string}
type Hypothesis={id:string;summary:string;confidence:string;evidenceIds:string[];alternatives:string[];nextStep:string}
type Change={id:string;summary:string;files:string[];tests:string[]}
type Proposal={id:string;summary:string;status:string;riskLevel:string;expectedEffect:string;riskStatement:string;verificationPlan:string}
type Receipt={destinationId:string;provider:string;status:string;attempts:number;response?:string;deliveredAt?:string}
type Update={id:string;status:string;body:string;updateType:string;audience:string;redactions:string[];destinations:Receipt[];approvedBy?:string}
type Finding={id:string;severity:string;category:string;assessment:string;recommendation:string;owner?:string;verificationMethod:string;status:string;evidenceRefs:string[]}
type Verification={status:string;checkedAt:string;signals:Evidence[]}
type Incident={id:string;serviceId:string;status:string;baselineStart:string;baselineEnd:string;incidentStart:string;incidentEnd:string;evidence:Evidence[];timeline:Event[];hypotheses:Hypothesis[];changes:Change[];proposals:Proposal[];updates:Update[];auditFindings:Finding[];verification?:Verification}
type Destination={id:string;provider:string}

const iso=(offset:number)=>new Date(Date.now()+offset).toISOString()
const label=(value:string)=>value.replaceAll("_"," ")
const measure=(value:number,unit:string)=>`${value.toLocaleString(undefined,{maximumFractionDigits:1})}${unit?` ${unit}`:""}`
const normalizeIncident=(incident:Incident):Incident=>({...incident,hypotheses:incident.hypotheses??[],changes:incident.changes??[],proposals:incident.proposals??[],updates:incident.updates??[],auditFindings:incident.auditFindings??[],timeline:incident.timeline??[],evidence:incident.evidence??[]})
async function post<T>(path:string,body:unknown):Promise<T>{const r=await fetch(path,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});if(!r.ok)throw new Error((await r.json().catch(()=>null))?.error??"Request failed");return r.json()}

function SignalChart({item}:{item:Evidence}){const data=useMemo(()=>[{window:"Base",value:item.baselineValue},{window:"Incident",value:item.incidentValue},{window:"Now",value:item.currentValue??item.incidentValue}],[item]);return <div className="mini-chart"><AreaChart data={data} config={{value:{label:item.signal,color:"blue"}}} margins={{left:8,bottom:24}}><XAxis dataKey="window"/><Tooltip labelKey="window" valueFormatter={n=>measure(n,item.unit)} variant="frosted-glass"/><Area dataKey="value" variant="gradient"/></AreaChart></div>}

export default function App(){
  const [services,setServices]=useState<Service[]>([]),[service,setService]=useState<Service|null>(null),[incident,setIncident]=useState<Incident|null>(null),[destinations,setDestinations]=useState<Destination[]>([]),[chosen,setChosen]=useState<string[]>([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState("")
  const refresh=async(id=incident?.id)=>{if(id)setIncident(normalizeIncident(await fetch(`/api/incidents/${id}`).then(r=>r.json())))}
  useEffect(()=>{Promise.all([fetch("/api/services").then(r=>r.json()),fetch("/api/incidents").then(r=>r.json()),fetch("/api/communications/destinations").then(r=>r.json())]).then(([s,i,d])=>{setServices(s);setService(s[0]??null);setIncident(i[0]?normalizeIncident(i[0]):null);setDestinations(d)}).catch(()=>setNotice("Mica is unavailable."))},[])
  useEffect(()=>{if(!incident)return;const stream=new EventSource(`/api/events?incidentId=${incident.id}`);stream.addEventListener("incident-update",()=>refresh(incident.id));return()=>stream.close()},[incident?.id])
  const run=async(work:()=>Promise<Incident>,message:string)=>{setBusy(true);try{setIncident(normalizeIncident(await work()));setNotice(message)}catch(e){setNotice(e instanceof Error?e.message:"Request failed")}finally{setBusy(false)}}
  const compare=()=>service&&run(()=>post("/api/incidents/detect",{serviceId:service.id,baselineStart:iso(-210000),baselineEnd:iso(-120000),incidentStart:iso(-110000),incidentEnd:iso(0)}),"Comparison saved.")
  const verify=()=>incident&&run(()=>post(`/api/incidents/${incident.id}/verify`,{verificationStart:iso(-90000),verificationEnd:iso(0)}),"Recovery check saved.")
  const prepare=()=>incident&&run(()=>post(`/api/incidents/${incident.id}/updates`,{updateType:"investigation_update",audience:"engineering",destinationIds:chosen,preparedBy:"Operator"}),"Draft ready.")
  const publish=(update:Update)=>{const approvedBy=window.prompt("Name the approver for this send:");if(!approvedBy?.trim())return;return incident&&run(()=>post(`/api/incidents/${incident.id}/updates/${update.id}/publish`,{approvedBy:approvedBy.trim()}),"Update sent.")}
  const review=(p:Proposal,status:"reviewed"|"deferred"|"rejected")=>incident&&run(()=>post(`/api/incidents/${incident.id}/proposals/${p.id}/review`,{status,reviewer:"Operator",note:"Reviewed in Mica"}),`Proposal ${status}.`)
  const submit=(path:string,body:(f:FormData)=>unknown,message:string)=>(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!incident)return;const form=e.currentTarget;run(()=>post(`/api/incidents/${incident.id}/${path}`,body(new FormData(form))),message);form.reset()}
  const copy=async()=>{if(!incident)return;await navigator.clipboard.writeText(await fetch(`/api/incidents/${incident.id}/report`).then(r=>r.text()));setNotice("Markdown report copied.")}
  if(!incident)return <main className="app"><Header/><section className="empty"><b>No comparisons yet.</b><span>Select a service, then compare two time windows.</span></section></main>
  const activeService=services.find(s=>s.id===incident.serviceId)??service
  const degraded=incident.evidence.filter(item=>item.classification==="degraded")
  const detected=degraded.length>0
  const brief=detected?`${degraded.length} signal${degraded.length===1?" is":"s are"} outside the healthy range.`:"No material regression in this comparison."
  const next=detected?"Review the changed signals, then record the next step.":"No action needed. Trigger the N+1 scenario to test the investigation flow."
  return <main className="app"><Header/><section className="incident-bar"><div><i className={`dot ${incident.status}`}/><b>{label(incident.status)}</b><span>#{incident.id.slice(-8)}</span></div><span>{activeService?.owners?.join(", ")||"Owner not configured"}</span><time>{new Date(incident.incidentEnd).toLocaleString()}</time></section>
    <section className={`decision ${detected?"attention":"clear"}`}><div><small>Prometheus · {activeService?.environment||"local"} · baseline vs. current</small><h1>{brief}</h1><p>{detected?"Values are from the saved baseline and current collection window.":"No required signal exceeded its configured tolerance in this window."}</p></div><div className="next-step"><small>Next</small><b>{next}</b></div></section>
    <section className="signal-strip">{incident.evidence.map(e=><div key={e.id}><span>{e.signal}</span><b className={e.classification}>{e.percentDelta>0?"+":""}{e.percentDelta.toFixed(0)}%</b><small>{label(e.classification)}</small></div>)}</section>
    <section className="content"><div><Title title="Evidence" detail="Baseline → incident → now"/><div className="chart-grid">{incident.evidence.map(e=><article className="chart-card" key={e.id}><div><b>{e.signal}</b><span className={e.classification}>{label(e.classification)}</span></div><SignalChart item={e}/><footer><span>{measure(e.baselineValue,e.unit)}</span><span>{measure(e.currentValue??e.incidentValue,e.unit)}</span></footer><details><summary>Provenance</summary><code>{e.query}</code><p>Healthy: {new Date(incident.baselineStart).toLocaleString()} → {new Date(incident.baselineEnd).toLocaleString()}</p><p>Collected by Mica telemetry comparison.</p></details></article>)}</div></div><aside className="activity"><Title title="Activity" detail={<><button onClick={copy}>Copy</button><a href={`/api/incidents/${incident.id}/report`} download>Download</a></>}/>{incident.timeline.slice().reverse().slice(0,6).map(e=><div className="event" key={e.id}><i/><span>{e.summary}<small>{e.actorName??"Mica"} · {new Date(e.occurredAt).toLocaleTimeString()}</small></span></div>)}<div className="quick-actions"><button onClick={verify} disabled={busy}>Verify recovery</button><span>{incident.verification?label(incident.verification.status):"Not verified"}</span></div></aside></section>
    <section className="records"><Panel title="Service context" count={activeService?.source?.kind||"configured"}><div className="context"><div><small>Repository</small><b>{activeService?.repository||"Not configured"}</b></div><div><small>Runtime</small><b>{[activeService?.runtime,activeService?.framework].filter(Boolean).join(" · ")||"Not configured"}</b></div><div><small>Dependencies</small><b>{activeService?.dependencies?.join(", ")||"None configured"}</b></div><div><small>Runbooks</small><b>{activeService?.runbooks?.join(", ")||"Not configured"}</b></div></div></Panel>
      <Panel title="Investigation" count={`${incident.hypotheses.length+incident.changes.length} records`}><div className="record-grid"><form onSubmit={submit("hypotheses",f=>({summary:f.get("summary"),confidence:"medium",evidenceIds:incident.evidence.slice(0,1).map(x=>x.id),alternatives:[String(f.get("alternative")||"Unconfirmed alternative")],nextStep:f.get("nextStep")}),"Hypothesis saved.")}><b>Record hypothesis</b><input name="summary" required placeholder="Evidence-backed explanation"/><input name="alternative" placeholder="Alternative explanation"/><input name="nextStep" required placeholder="Safe next step"/><button>Save</button></form><form onSubmit={submit("changes",f=>({summary:f.get("summary"),files:String(f.get("files")||"").split("\n").filter(Boolean),tests:String(f.get("tests")||"").split("\n").filter(Boolean)}),"Change saved.")}><b>Record code change</b><input name="summary" required placeholder="What changed?"/><textarea name="files" placeholder="Files changed, one per line"/><textarea name="tests" placeholder="Tests run, one per line"/><button>Save</button></form>{incident.hypotheses.map(h=><article className="saved" key={h.id}><b>Hypothesis · {h.confidence}</b><p>{h.summary}</p><small>Evidence: {h.evidenceIds.join(", ")||"none"} · Next: {h.nextStep}</small></article>)}{incident.changes.map(c=><article className="saved" key={c.id}><b>Change</b><p>{c.summary}</p><small>{c.files.join(", ")||"No files listed"} · {c.tests.join(", ")||"No tests listed"}</small></article>)}</div></Panel>
      <Panel title="Human controls" count={`${incident.proposals.length} proposals`}><div className="record-grid">{incident.proposals.map(p=><article className="saved" key={p.id}><b>{p.summary}</b><small>{p.riskLevel} · {label(p.status)}</small><p>{p.expectedEffect}</p><small>Risk: {p.riskStatement} · Verify: {p.verificationPlan}</small>{p.status==="pending_review"&&<div className="review"><button onClick={()=>review(p,"reviewed")}>Review</button><button onClick={()=>review(p,"deferred")}>Defer</button><button onClick={()=>review(p,"rejected")}>Reject</button></div>}</article>)}<form onSubmit={submit("notes",f=>({note:f.get("note"),actor:"Operator"}),"Note saved.")}><b>Add context</b><textarea name="note" required placeholder="What the telemetry cannot tell us"/><button>Save note</button></form></div></Panel>
      <Panel title="Recovery" count={incident.verification?label(incident.verification.status):"Awaiting fresh telemetry"}>{incident.verification?<div className="verification">{incident.verification.signals.map(s=><div key={s.id}><b>{s.signal}</b><span>{measure(s.currentValue??s.incidentValue,s.unit)}</span><small className={s.classification}>{label(s.classification)}</small></div>)}</div>:<p className="muted">Run verification only after a recorded change and fresh telemetry.</p>}</Panel>
      <Panel title="External delivery" count={`${incident.updates.length} drafts`}><div className="record-grid"><article className="saved"><b>Redacted update</b><div className="channels">{destinations.length?destinations.map(d=><label key={d.id}><input type="checkbox" checked={chosen.includes(d.id)} onChange={()=>setChosen(c=>c.includes(d.id)?c.filter(x=>x!==d.id):[...c,d.id])}/>{d.provider}</label>):<small>No destination configured; a local-only draft can still be prepared.</small>}</div>{destinations.length?<button className="link-button" onClick={()=>setChosen(destinations.map(d=>d.id))}>Select all</button>:null}<button onClick={prepare}>Prepare preview</button></article>{incident.updates.map(u=><article className="saved" key={u.id}><b>{label(u.updateType)} · {label(u.status)}</b><small>Audience: {u.audience} · Redactions: {u.redactions.join(", ")||"none"}</small><pre>{u.body}</pre><div className="receipts">{u.destinations.map(d=><span key={d.destinationId}>{d.provider}: {d.status} ({d.attempts})</span>)}</div>{u.status==="pending_approval"?<button onClick={()=>publish(u)}>Approve & publish</button>:null}</article>)}</div></Panel>
      <Panel title="Audit findings" count={`${incident.auditFindings.length} findings`}><div className="finding-list">{incident.auditFindings.length?incident.auditFindings.map(f=><article className={`finding ${f.severity}`} key={f.id}><b>{f.severity} · {f.category}</b><p>{f.assessment}</p><small>Evidence: {f.evidenceRefs.join(", ")||"unknown"} · Verify: {f.verificationMethod}</small><p>Recommendation: {f.recommendation}</p></article>):<p className="muted">No audit findings have been recorded for this incident.</p>}</div></Panel>
    </section>{notice&&<p className="notice">{notice}</p>}<footer>Local incident record · Prometheus comparison windows</footer>
  </main>
  function Header(){return <header><a href="/" className="brand">mica<span>.</span></a><label className="service-picker"><span>Service</span><select value={service?.id??""} onChange={e=>setService(services.find(s=>s.id===e.target.value)??null)}>{services.map(s=><option value={s.id} key={s.id}>{s.name} · {s.environment}</option>)}</select></label><button className="compare" onClick={compare} disabled={busy}>{busy?"Comparing…":"Compare"}</button><span className="mode">Read-only by default</span></header>}
}
function Title({title,detail}:{title:string;detail:ReactNode}){return <div className="section-title"><p>{title}</p><span>{detail}</span></div>}
function Panel({title,count,children}:{title:string;count:string;children:ReactNode}){return <details className="panel"><summary>{title}<span>{count}</span></summary><div className="panel-body">{children}</div></details>}
