// Package web exposes the generated React workspace as an embedded filesystem.
package web

import (
	"embed"
	"io/fs"
)

// Assets are generated by `make web-embed` (and by the Docker build) before
// producing a distributable Mica binary.
//
//go:embed all:dist
var assets embed.FS

func Assets() fs.FS {
	files, err := fs.Sub(assets, "dist")
	if err != nil {
		panic(err)
	}
	return files
}
